export const mockDoctors = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    clinic: "Heart Care Center",
    location: "Downtown Medical Plaza",
    rating: 4.8,
    reviews: 124,
    experience: "15 years",
    nextAvailable: "Today 2:00 PM",
    image: "/placeholder.svg?height=100&width=100",
    consultationFee: 150,
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Dermatologist",
    clinic: "Skin Health Clinic",
    location: "Medical Center West",
    rating: 4.9,
    reviews: 89,
    experience: "12 years",
    nextAvailable: "Tomorrow 10:30 AM",
    image: "/placeholder.svg?height=100&width=100",
    consultationFee: 120,
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    specialty: "Pediatrician",
    clinic: "Children's Health Center",
    location: "Family Medical Building",
    rating: 4.7,
    reviews: 156,
    experience: "10 years",
    nextAvailable: "Today 4:15 PM",
    image: "/placeholder.svg?height=100&width=100",
    consultationFee: 100,
  },
]